#pragma once
#include <vector>
#include <string>
#include "Character.h"

/// <summary>
/// This is where any new characters can be generated by factory method
/// </summary>
class CharacterFactory
{

public:
	std::vector<std::string> ListAllCharacterOptions();

	Character GenerateWoodElf();
	Character GenerateDwarf();
	Character GenerateEnchantress();
};

